### ISSUE TITLE
Suggestion: Instead of map(), use find()

### ISSUE THREAD

**Issue by DeimonDB** [mrlepak/seedly-take-home-challenge#1]
https://github.com/mrlepak/seedly-take-home-challenge/blob/4d9b42ffcb3132bbc778497b6139cc85db017ba3/src/components/Banner.js#L10-L15

`.map` is not the right function to be used here. As its name suggests, it is to map the values of an array into another value by applying a given functions. For example, mapping [1, 2, 3] into [2, 3, 4] by giving a `function plusOne(x) { return x + 1; }` function.

In your code, what you are essentially doing is to find a `topic` that matches the given `topicName`. For this, substitute the map into `forEach`, Or even better, use `.find()`:

```
const foundTopic = topics.find(topic => topic.name == chosenTopic);
displayHeader = foundTopic.name;
displaySubHeader = foundTopic.content;
```

**Comment by mister-lepak** [comment]
Have always seen map as the almighty iterator. lol!
thanks for shedding a new light to the nuances of .map() and elegance of .find()!
