### ISSUE TITLE
Suggestion: Use early return, and be careful of code flow without return value

### ISSUE THREAD

**Issue by DeimonDB** [mrlepak/seedly-take-home-challenge#2]
https://github.com/mrlepak/seedly-take-home-challenge/blob/4d9b42ffcb3132bbc778497b6139cc85db017ba3/src/components/QnA.js#L54-L66

## Code flow without return value
In this code what happens if the `chosenTopic` is not null, but not found in `topics` array?
Yes it will eventually go to line 64, ending terminating the function without any return value.

This is considered bad practice, and should be handled properly. A return statement should be added at the end of every possible code paths.

## Early Return

Suggesting to change the code structure to use `early return` pattern https://medium.com/swlh/return-early-pattern-3d18a41bba8 

```
return questions.map((question) => {
      if (chosenTopic != "" && chosenTopic_not_exist()) {
        return null;
      }
      return renderQuestionDetails(question);
});
```

the part of `chosenTopic_not_exist`, can be implemented using `.find()` mentioned in https://github.com/mrlepak/seedly-take-home-challenge/issues/1

**Comment by mister-lepak** [comment]
wow.. this pattern is mind blowing.
Thanks for sharing!
updated in the new commit.
