### ISSUE TITLE
Suggestion: General variable naming, and to use `filter` and `find`

### ISSUE THREAD

**Issue by DeimonDB** [mrlepak/seedly-take-home-challenge#3]
https://github.com/mrlepak/seedly-take-home-challenge/blob/4d9b42ffcb3132bbc778497b6139cc85db017ba3/src/components/QnA.js#L7-L20

## Naming
Assuming the code stays this way, I will rename the variables to be more readable
* `topic` rename to `questionTopicID`
* `element` rename to `topic`

## Filter and Find
The code IMO is too nested. We could be remove the code nesting by changing the flow slightly, and  utilizing `.filter()` and `.find()`.

Flow:
1. `map`: map the `questionTopicID` to `topic`, by utilizing `find`
2. `Filter`: remove all the questionTopic that is null (not found in `topics` array)
3. `map`:  since now we know all the questions are valid, we can map them to React objects without any validations.

```
return question.topics
 .map((questionTopicID) => topics.find(topic => topic.id == questionTopicID) ) // step 1
 .filter(questionTopic => questionTopic != null) // step 2 remove all nulls
 .map(questionTopic => (<Link className="ui button" to={"/topic/" + element.name}>  // step 3 convert to react object
             {element.name} 
           </Link> ));
```

**Comment by mister-lepak** [comment]
updated! :)
